# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-16 05:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fragrance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fragrance_name', models.CharField(max_length=200)),
            ],
        ),
    ]
