# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-16 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_auto_20160516_0528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fragrance',
            name='quantity',
        ),
        migrations.AddField(
            model_name='fragrance',
            name='size',
            field=models.FloatField(default=1.7),
            preserve_default=False,
        ),
    ]
